### ISSUE TITLE
Can't build this project with mingw32-make.exe

### ISSUE THREAD

**Issue by p506738532** [ssbssa/heob#13] opened 2018-08-14 14:11 UTC
environment:Win10,QT5.7.0-mingW.
In cmd.exe,input the commond:
`D:\ProgramFiles\Qt\heob\heob-master\heob-master>D:\ProgramFiles\Qt\Qt5.7.0\Tools\mingw530_32\bin\mingw32-make.exe  CPPFLAGS="-DNO_DWARFSTACK"`
There is an error when i input an "enter"
`Makefile:54: *** multiple target patterns.  Stop.`
what's wrong with my operation?
3Q!

**Comment by ssbssa** [comment] 2018-08-14 15:32
Well, I have never used mingw32-make.exe (I usually use the MSYS2 make), so I have to check what could be wrong here.

**Comment by ssbssa** [comment] 2018-08-14 16:36
Where did you get the mingw32-make.exe?

**Comment by p506738532** [comment] 2018-08-14 16:41
soga,i didn't know where the make.exe is.MSYS2 is not installed in myy computer.can i compile the project with qt creator?

**Comment by ssbssa** [comment] 2018-08-14 16:46
Yes, you can compile with qt creator, you have to use heob.qbs for that.

**Comment by p506738532** [comment] 2018-08-14 16:47
i have download qt-creator-mingw-5.7.0 and find it in "xx/tools/mingw32/bin" path.

**Comment by p506738532** [comment] 2018-08-14 16:48
but qt creator said can't find profile

**Comment by ssbssa** [comment] 2018-08-14 16:50
what profile?

**Comment by p506738532** [comment] 2018-08-14 16:58
In qt creator ，Equivalent command line：
`D:\ProgramFiles\Qt\Qt5.7.0\Tools\QtCreator\bin\qbs.exe build -d D:\ProgramFiles\Qt\heob\heob-master\build-heob-Desktop_Qt_5_7_0_MinGW_CDB_32bit-Release -f D:\ProgramFiles\Qt\heob\heob-master\heob-master\heob.qbs --settings-dir C:\Users\Administrator\AppData\Roaming\QtProject\qtcreator --jobs 4 release profile:qtc_Desktop__a9a623b5`
can‘t find profile:qtc_Desktop__a9a623b5

**Comment by p506738532** [comment] 2018-08-14 16:59
There is an error ":-1: error: Unknown or empty profile 'qtc_Desktop__a9a623b5'."when i open the heob.qbs with qt creator.

**Comment by ssbssa** [comment] 2018-08-14 17:13
I will have to see if I can reproduce the error if I use the qt 5.7.0, because I have had no such problem with 5.9 - 5.11 so far.

**Comment by p506738532** [comment] 2018-08-14 17:15
![heobbuilderror](https://user-images.githubusercontent.com/16209077/44106951-8b1eef9a-a028-11e8-81e3-17a15dbfcbd5.PNG)
There is an error like this.

**Comment by ssbssa** [comment] 2018-08-14 17:17
I'm downloading qt-mingw-5.7.0 right now, but is there some reason you don't use a newer qt version?

**Comment by p506738532** [comment] 2018-08-14 17:28
i have build it successfully with qt5.9.0. But I can't find the output .exe file.what should i config?

**Comment by ssbssa** [comment] 2018-08-14 17:34
What build directory is configured, it should be in there.

**Comment by p506738532** [comment] 2018-08-14 17:37
After builed.there are two files in the "Build direction":
`qtc_Desktop__c4fafcbf-release.bg` and `qtc_Desktop__c4fafcbf-release.bg.lock`.I don't know what is the output .exe file named.

**Comment by ssbssa** [comment] 2018-08-14 17:41
The the build probably didn't finish successfully, you should see some errors or at least warnings in the Issues pane.

**Comment by p506738532** [comment] 2018-08-14 17:45
there is some info
`Running Windows Runtime device detection.
D:/ProgramFiles/Qt/Qt5.9.0/5.9.1/winrt_armv7_msvc2015/bin/winrtrunner.exe --list-devices
No build graph exists yet for this configuration.
Build done for configuration qtc_Desktop__a9a623b5-release.
Build done for configuration qtc_Desktop__a9a623b5-release.
Build done for configuration qtc_Desktop__a9a623b5-release.
Build done for configuration qtc_Desktop__a9a623b5-release.`

**Comment by ssbssa** [comment] 2018-08-14 17:49
Are you trying to build it for armv7?

**Comment by p506738532** [comment] 2018-08-14 17:49
there are some warnings:
`D:\ProgramFiles\Qt\heob\heob-master\heob-master\heob.qbs:4: warning: Referenced directory 'D:/ProgramFiles/Qt/heob/heob-master/heob-master/dwarfstack/dwarfstack.qbs' does not contain a qbs file.`
`D:\ProgramFiles\Qt\heob\heob-master\heob-master\heob.qbs:17: warning: Dependency 'dwarfstack' not found for product 'heob'.`
`D:\ProgramFiles\Qt\heob\heob-master\heob-master\heob.qbs:6: warning: Product 'heob' had errors and was disabled.`

**Comment by ssbssa** [comment] 2018-08-14 17:49
Ok, that is good information, you don't have the dwarfstack git submodule.

**Comment by p506738532** [comment] 2018-08-14 17:50
no.I just want to build for my win10.

**Comment by p506738532** [comment] 2018-08-14 17:51
the dwarfstack is necessary?

**Comment by ssbssa** [comment] 2018-08-14 17:52
If you want to use heob for mingw executables, yes.

In that case you should call in the heob directory:
`git submodule update --init`

**Comment by ssbssa** [comment] 2018-08-14 17:55
If you don't need it for mingw binaries, you can remore the `references` line, and change the cpp.defines to:
`cpp.defines: [ "HEOB_VER=\"" + heob_ver + "\"", "NO_DWARFSTACK" ]`

**Comment by p506738532** [comment] 2018-08-14 18:03
i am trying to downling the dwarfstack.thank you very much!

**Comment by ssbssa** [comment] 2018-08-14 18:10
Is there a special reason you need to compile heob yourself, and not use the release?

**Comment by p506738532** [comment] 2018-08-14 18:26
i have built the heob32.exe and dwarfstack32.dll successfully.thanks again.

**Comment by ssbssa** [comment] 2018-08-14 18:30
So I guess I can close this.

Feel free to reopen if you have further problems/questions.

**Closed by ssbssa** 2018-08-14 18:30 UTC
Labels: question
